<template><JPageSiteMap :breadcrumb="breadcrumb" :groupConfig="groupConfig" :groupOptions="groupOptions" /></template>
<script>
export default {
    data() {
        return {
            breadcrumb: [{ title: 'Trang chủ', link: '/' }, { title: 'Site map' }],
            groupConfig: [
                {
                    title: 'Trang chủ',
                    nodes: [
                        { title: 'Trang chủ', link: '/' },
                        { title: 'Về chúng tôi', link: '/ve-chung-toi' },
                        { title: 'Tuyển dụng', link: '/tuyển dụng' },
                    ],
                },
                {
                    title: 'Tin tức',
                    nodes: [
                        { title: 'Tin nội bộ', link: '/' },
                        { title: 'Tin chuyên ngành', link: '/tin-chuyen-nganh' },
                        { title: 'Tin quốc tế', link: '/tuyển dụng' },
                        { title: 'Tin thị trường', link: '/' },
                    ],
                },
                {
                    title: 'Dịch vụ',
                    nodes: [
                        { title: 'Tên dịch vụ a', link: '/' },
                        { title: 'Tên dịch vụ b', link: '/tin-chuyen-nganh' },
                        { title: 'Tên dịch vụ c', link: '/tuyển dụng' },
                        { title: 'Tên dịch vụ d', link: '/' },
                    ],
                },
                {
                    title: 'Chính sách',
                    nodes: [
                        { title: 'Chính sách mua hàng', link: '/' },
                        { title: 'Chính sách vận chuyển', link: '/tin-chuyen-nganh' },
                        { title: 'Chính sách đổi trả', link: '/tuyển dụng' },
                        { title: 'Chính sách bảo hành', link: '/' },
                    ],
                },
            ],
            groupOptions: [
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
                {
                    title: 'Danh mục sản phẩm level 1 (1)',
                    nodes: [
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                        { title: 'Tên sản phẩm (level 2)', link: '/' },
                    ],
                },
            ],
        }
    },
}
</script>
