<template>
    <JPageBlogCategory
        :bannerTop="bannerTop"
        :breadcrumb="breadcrumb"
        :top_posts="top_posts"
        :top_views="top_views"
        :posts_data="posts_data"
        :posts="posts"
        :banner="banner"
        :categories="categories"
        :currentPath="currentPath"
    />
</template>

<script>
export default {
    data() {
        return {
            currentPath: this.$route.path,
            breadcrumb: [
                {
                    title: 'Trang chủ',
                    link: '/',
                },
                {
                    title: 'Tin tức',
                },
            ],
            posts_data: [
                {
                    id: 85,
                    title: 'Quae rerum non aut tenetur.',
                    slug: 'quae-rerum-non-aut-tenetur',
                    published_at: '2023-03-08',
                    description:
                        'A harum velit fugit culpa facilis repellat. Dolore ut quia placeat aspernatur sapiente in distinctio. Quia est voluptatem provident id.',
                    category: {
                        id: 24,
                        title: 'Hic earum vel facilis.',
                        slug: 'hic-earum-vel-facilis',
                        image: { url: null, alt: 'Hic earum vel facilis.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                    },
                    categories: [
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Quae rerum non aut tenetur.' },
                    url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis/quae-rerum-non-aut-tenetur',
                },
                {
                    id: 77,
                    title: 'Nam laboriosam.',
                    slug: 'nam-laboriosam',
                    published_at: '2023-03-08',
                    description:
                        'Eveniet maxime velit modi rerum molestiae. Accusantium qui sequi sunt commodi doloribus cum.',
                    category: {
                        id: 3,
                        title: 'Sit non.',
                        slug: 'sit-non',
                        image: { url: null, alt: 'Sit non.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/sit-non',
                    },
                    categories: [
                        {
                            id: 3,
                            title: 'Sit non.',
                            slug: 'sit-non',
                            image: { url: null, alt: 'Sit non.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/sit-non',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Nam laboriosam.' },
                    url: 'http://localhost:8000/tin-tuc/sit-non/nam-laboriosam',
                },
                {
                    id: 44,
                    title: 'Sit omnis sint vel.',
                    slug: 'sit-omnis-sint-vel',
                    published_at: '2023-03-08',
                    description:
                        'Ex quae explicabo et porro eveniet. Molestiae nulla quae accusantium necessitatibus sequi et beatae. Quas molestiae laboriosam in quis saepe dolores. Exercitationem tenetur totam voluptas similique.',
                    category: {
                        id: 16,
                        title: 'Odit alias pariatur.',
                        slug: 'odit-alias-pariatur',
                        image: { url: null, alt: 'Odit alias pariatur.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                    },
                    categories: [
                        {
                            id: 16,
                            title: 'Odit alias pariatur.',
                            slug: 'odit-alias-pariatur',
                            image: { url: null, alt: 'Odit alias pariatur.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Sit omnis sint vel.' },
                    url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur/sit-omnis-sint-vel',
                },
                {
                    id: 85,
                    title: 'Quae rerum non aut tenetur.',
                    slug: 'quae-rerum-non-aut-tenetur',
                    published_at: '2023-03-08',
                    description:
                        'A harum velit fugit culpa facilis repellat. Dolore ut quia placeat aspernatur sapiente in distinctio. Quia est voluptatem provident id.',
                    category: {
                        id: 24,
                        title: 'Hic earum vel facilis.',
                        slug: 'hic-earum-vel-facilis',
                        image: { url: null, alt: 'Hic earum vel facilis.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                    },
                    categories: [
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Quae rerum non aut tenetur.' },
                    url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis/quae-rerum-non-aut-tenetur',
                },
                {
                    id: 77,
                    title: 'Nam laboriosam.',
                    slug: 'nam-laboriosam',
                    published_at: '2023-03-08',
                    description:
                        'Eveniet maxime velit modi rerum molestiae. Accusantium qui sequi sunt commodi doloribus cum.',
                    category: {
                        id: 3,
                        title: 'Sit non.',
                        slug: 'sit-non',
                        image: { url: null, alt: 'Sit non.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/sit-non',
                    },
                    categories: [
                        {
                            id: 3,
                            title: 'Sit non.',
                            slug: 'sit-non',
                            image: { url: null, alt: 'Sit non.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/sit-non',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Nam laboriosam.' },
                    url: 'http://localhost:8000/tin-tuc/sit-non/nam-laboriosam',
                },
                {
                    id: 44,
                    title: 'Sit omnis sint vel.',
                    slug: 'sit-omnis-sint-vel',
                    published_at: '2023-03-08',
                    description:
                        'Ex quae explicabo et porro eveniet. Molestiae nulla quae accusantium necessitatibus sequi et beatae. Quas molestiae laboriosam in quis saepe dolores. Exercitationem tenetur totam voluptas similique.',
                    category: {
                        id: 16,
                        title: 'Odit alias pariatur.',
                        slug: 'odit-alias-pariatur',
                        image: { url: null, alt: 'Odit alias pariatur.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                    },
                    categories: [
                        {
                            id: 16,
                            title: 'Odit alias pariatur.',
                            slug: 'odit-alias-pariatur',
                            image: { url: null, alt: 'Odit alias pariatur.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Sit omnis sint vel.' },
                    url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur/sit-omnis-sint-vel',
                },
                {
                    id: 44,
                    title: 'Sit omnis sint vel.',
                    slug: 'sit-omnis-sint-vel',
                    published_at: '2023-03-08',
                    description:
                        'Ex quae explicabo et porro eveniet. Molestiae nulla quae accusantium necessitatibus sequi et beatae. Quas molestiae laboriosam in quis saepe dolores. Exercitationem tenetur totam voluptas similique.',
                    category: {
                        id: 16,
                        title: 'Odit alias pariatur.',
                        slug: 'odit-alias-pariatur',
                        image: { url: null, alt: 'Odit alias pariatur.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                    },
                    categories: [
                        {
                            id: 16,
                            title: 'Odit alias pariatur.',
                            slug: 'odit-alias-pariatur',
                            image: { url: null, alt: 'Odit alias pariatur.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Sit omnis sint vel.' },
                    url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur/sit-omnis-sint-vel',
                },
                {
                    id: 85,
                    title: 'Quae rerum non aut tenetur.',
                    slug: 'quae-rerum-non-aut-tenetur',
                    published_at: '2023-03-08',
                    description:
                        'A harum velit fugit culpa facilis repellat. Dolore ut quia placeat aspernatur sapiente in distinctio. Quia est voluptatem provident id.',
                    category: {
                        id: 24,
                        title: 'Hic earum vel facilis.',
                        slug: 'hic-earum-vel-facilis',
                        image: { url: null, alt: 'Hic earum vel facilis.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                    },
                    categories: [
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Quae rerum non aut tenetur.' },
                    url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis/quae-rerum-non-aut-tenetur',
                },
                {
                    id: 77,
                    title: 'Nam laboriosam.',
                    slug: 'nam-laboriosam',
                    published_at: '2023-03-08',
                    description:
                        'Eveniet maxime velit modi rerum molestiae. Accusantium qui sequi sunt commodi doloribus cum.',
                    category: {
                        id: 3,
                        title: 'Sit non.',
                        slug: 'sit-non',
                        image: { url: null, alt: 'Sit non.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/sit-non',
                    },
                    categories: [
                        {
                            id: 3,
                            title: 'Sit non.',
                            slug: 'sit-non',
                            image: { url: null, alt: 'Sit non.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/sit-non',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Nam laboriosam.' },
                    url: 'http://localhost:8000/tin-tuc/sit-non/nam-laboriosam',
                },
                {
                    id: 44,
                    title: 'Sit omnis sint vel.',
                    slug: 'sit-omnis-sint-vel',
                    published_at: '2023-03-08',
                    description:
                        'Ex quae explicabo et porro eveniet. Molestiae nulla quae accusantium necessitatibus sequi et beatae. Quas molestiae laboriosam in quis saepe dolores. Exercitationem tenetur totam voluptas similique.',
                    category: {
                        id: 16,
                        title: 'Odit alias pariatur.',
                        slug: 'odit-alias-pariatur',
                        image: { url: null, alt: 'Odit alias pariatur.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                    },
                    categories: [
                        {
                            id: 16,
                            title: 'Odit alias pariatur.',
                            slug: 'odit-alias-pariatur',
                            image: { url: null, alt: 'Odit alias pariatur.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Sit omnis sint vel.' },
                    url: 'http://localhost:8000/tin-tuc/odit-alias-pariatur/sit-omnis-sint-vel',
                },
            ],

            bannerTop: {
                image: {
                    url: 'https://via.placeholder.com/900x300',
                    alt: 'banner blog category',
                },
            },

            top_posts: [
                {
                    id: 191,
                    title: 'Những điều bạn cần biết về tối ưu nội dung SEO trong năm 2023',
                    slug: 'dolorem-non',
                    published_at: '2023-03-08',
                    description:
                        'Sự ra đời của ChatGPT đang gây bão trong khoảng thời gian gần đây chắc chắn sẽ gây ảnh hưởng không nhỏ đến hoạt động của các chỉ số danh giá SEO.',
                    category: {
                        id: 4,
                        title: 'Dolorem cumque.',
                        slug: 'dolorem-cumque',
                        image: { url: null, alt: 'Dolorem cumque.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/dolorem-cumque',
                    },
                    categories: [
                        {
                            id: 4,
                            title: 'Dolorem cumque.',
                            slug: 'dolorem-cumque',
                            image: { url: null, alt: 'Dolorem cumque.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/dolorem-cumque',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Dolorem non.' },
                    url: 'http://localhost:8000/tin-tuc/dolorem-cumque/dolorem-non',
                },
                {
                    id: 162,
                    title: 'Static Site Generator: Trình tạo trang tĩnh được ứng dụng trong kiến trúc website Jamstack3',
                    slug: 'inventore-id-ad',
                    published_at: '2023-03-08',
                    description:
                        'Dolores in et aut aut magnam. Labore dolores velit quas ut magnam. Sed quaerat sunt quia quidem. Dolore porro quisquam quia cumque.',
                    category: {
                        id: 24,
                        title: 'Hic earum vel facilis.',
                        slug: 'hic-earum-vel-facilis',
                        image: { url: null, alt: 'Hic earum vel facilis.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                    },
                    categories: [
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Inventore id ad.' },
                    url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis/inventore-id-ad',
                },
                {
                    id: 117,
                    title: 'Static Site Generator: Trình tạo trang tĩnh được ứng dụng trong kiến trúc website Jamstack3',
                    slug: 'officiis',
                    published_at: '2023-03-08',
                    description:
                        'Incidunt officiis omnis atque eius. Officia quia aut molestiae eius quisquam ut. Et molestias voluptatem iusto facere id qui.',
                    category: {
                        id: 2,
                        title: 'Libero ducimus in.',
                        slug: 'libero-ducimus-in',
                        image: { url: null, alt: 'Libero ducimus in.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/libero-ducimus-in',
                    },
                    categories: [
                        {
                            id: 2,
                            title: 'Libero ducimus in.',
                            slug: 'libero-ducimus-in',
                            image: { url: null, alt: 'Libero ducimus in.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/libero-ducimus-in',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Officiis.' },
                    url: 'http://localhost:8000/tin-tuc/libero-ducimus-in/officiis',
                },
                {
                    id: 102,
                    title: 'Static Site Generator: Trình tạo trang tĩnh được ứng dụng trong kiến trúc website Jamstack3',
                    slug: 'voluptas-est-maiores',
                    published_at: '2023-03-08',
                    description:
                        'Perspiciatis vel quaerat a in id voluptate. Voluptatem ad quia at esse blanditiis facere. Accusantium qui voluptas repudiandae et. Ad molestiae debitis ea.',
                    category: {
                        id: 8,
                        title: 'Quidem sit.',
                        slug: 'quidem-sit',
                        image: { url: null, alt: 'Quidem sit.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/quidem-sit',
                    },
                    categories: [
                        {
                            id: 8,
                            title: 'Quidem sit.',
                            slug: 'quidem-sit',
                            image: { url: null, alt: 'Quidem sit.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/quidem-sit',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Voluptas est maiores.' },
                    url: 'http://localhost:8000/tin-tuc/quidem-sit/voluptas-est-maiores',
                },
            ],

            top_views: [
                {
                    id: 191,
                    title: 'Dolorem non.',
                    slug: 'dolorem-non',
                    published_at: '2023-03-08',
                    description:
                        'Explicabo reprehenderit temporibus nihil velit qui omnis amet. Vel id consequatur facilis sint unde. Aut officiis natus quia quia nisi similique. Voluptates est culpa dolore aut.',
                    category: {
                        id: 4,
                        title: 'Dolorem cumque.',
                        slug: 'dolorem-cumque',
                        image: { url: null, alt: 'Dolorem cumque.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/dolorem-cumque',
                    },
                    categories: [
                        {
                            id: 4,
                            title: 'Dolorem cumque.',
                            slug: 'dolorem-cumque',
                            image: { url: null, alt: 'Dolorem cumque.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/dolorem-cumque',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Dolorem non.' },
                    url: 'http://localhost:8000/tin-tuc/dolorem-cumque/dolorem-non',
                },
                {
                    id: 162,
                    title: 'Inventore id ad.',
                    slug: 'inventore-id-ad',
                    published_at: '2023-03-08',
                    description:
                        'Dolores in et aut aut magnam. Labore dolores velit quas ut magnam. Sed quaerat sunt quia quidem. Dolore porro quisquam quia cumque.',
                    category: {
                        id: 24,
                        title: 'Hic earum vel facilis.',
                        slug: 'hic-earum-vel-facilis',
                        image: { url: null, alt: 'Hic earum vel facilis.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                    },
                    categories: [
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Inventore id ad.' },
                    url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis/inventore-id-ad',
                },
                {
                    id: 117,
                    title: 'Officiis.',
                    slug: 'officiis',
                    published_at: '2023-03-08',
                    description:
                        'Incidunt officiis omnis atque eius. Officia quia aut molestiae eius quisquam ut. Et molestias voluptatem iusto facere id qui.',
                    category: {
                        id: 2,
                        title: 'Libero ducimus in.',
                        slug: 'libero-ducimus-in',
                        image: { url: null, alt: 'Libero ducimus in.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/libero-ducimus-in',
                    },
                    categories: [
                        {
                            id: 2,
                            title: 'Libero ducimus in.',
                            slug: 'libero-ducimus-in',
                            image: { url: null, alt: 'Libero ducimus in.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/libero-ducimus-in',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Officiis.' },
                    url: 'http://localhost:8000/tin-tuc/libero-ducimus-in/officiis',
                },
                {
                    id: 102,
                    title: 'Voluptas est maiores.',
                    slug: 'voluptas-est-maiores',
                    published_at: '2023-03-08',
                    description:
                        'Perspiciatis vel quaerat a in id voluptate. Voluptatem ad quia at esse blanditiis facere. Accusantium qui voluptas repudiandae et. Ad molestiae debitis ea.',
                    category: {
                        id: 8,
                        title: 'Quidem sit.',
                        slug: 'quidem-sit',
                        image: { url: null, alt: 'Quidem sit.' },
                        icon: null,
                        url: 'http://localhost:8000/tin-tuc/quidem-sit',
                    },
                    categories: [
                        {
                            id: 8,
                            title: 'Quidem sit.',
                            slug: 'quidem-sit',
                            image: { url: null, alt: 'Quidem sit.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/quidem-sit',
                        },
                        {
                            id: 24,
                            title: 'Hic earum vel facilis.',
                            slug: 'hic-earum-vel-facilis',
                            image: { url: null, alt: 'Hic earum vel facilis.' },
                            icon: null,
                            url: 'http://localhost:8000/tin-tuc/hic-earum-vel-facilis',
                        },
                    ],
                    image: { url: null, alt: 'Voluptas est maiores.' },
                    url: 'http://localhost:8000/tin-tuc/quidem-sit/voluptas-est-maiores',
                },
            ],

            banner: {
                id: 2,
                title: '<p>Demo</p>',
                description: null,
                link: null,
                target: '_self',
                custom_fields: null,
                image: { url: 'https://via.placeholder.com/300x400', alt: 'Demo' },
                image_mobile: { url: null, alt: 'Demo' },
            },

            posts: {
                current_page: 1,
                data: [
                    {
                        id: 39,
                        title: 'Aut ut enim.',
                        slug: 'aut-ut-enim',
                        published_at: '2023-03-27',
                        description:
                            'Non fugiat aperiam atque maxime. Consequatur recusandae omnis optio. Qui ut molestiae ut ab aspernatur commodi eos. Maxime porro in atque.',
                        category: {
                            id: 12,
                            title: 'Omnis vero.',
                            slug: 'omnis-vero',
                            image: { url: null, alt: 'Omnis vero.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/omnis-vero',
                        },
                        categories: [
                            {
                                id: 12,
                                title: 'Omnis vero.',
                                slug: 'omnis-vero',
                                image: { url: null, alt: 'Omnis vero.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/omnis-vero',
                            },
                            {
                                id: 15,
                                title: 'Praesentium qui.',
                                slug: 'praesentium-qui',
                                image: { url: null, alt: 'Praesentium qui.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/praesentium-qui',
                            },
                        ],
                        image: { url: null, alt: 'Aut ut enim.' },
                        url: 'http://localhost:8000/posts/omnis-vero/aut-ut-enim',
                    },
                    {
                        id: 103,
                        title: 'Tempore non numquam amet.',
                        slug: 'tempore-non-numquam-amet',
                        published_at: '2023-03-27',
                        description:
                            'Quia voluptatem numquam aut sed sapiente et et. Maiores omnis sunt voluptates. Hic vel quia ab ipsum eveniet.',
                        category: {
                            id: 7,
                            title: 'Aut expedita.',
                            slug: 'aut-expedita',
                            image: { url: null, alt: 'Aut expedita.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/aut-expedita',
                        },
                        categories: [
                            {
                                id: 7,
                                title: 'Aut expedita.',
                                slug: 'aut-expedita',
                                image: { url: null, alt: 'Aut expedita.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/aut-expedita',
                            },
                            {
                                id: 15,
                                title: 'Praesentium qui.',
                                slug: 'praesentium-qui',
                                image: { url: null, alt: 'Praesentium qui.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/praesentium-qui',
                            },
                        ],
                        image: { url: null, alt: 'Tempore non numquam amet.' },
                        url: 'http://localhost:8000/posts/aut-expedita/tempore-non-numquam-amet',
                    },
                    {
                        id: 48,
                        title: 'Officiis.',
                        slug: 'officiis',
                        published_at: '2023-03-27',
                        description:
                            'Ut odit repellendus a. Accusamus debitis magni maiores labore est omnis. Accusamus ut harum consequuntur laborum ad aspernatur sint quia. Harum est odio ut sed.',
                        category: {
                            id: 6,
                            title: 'Amet libero rerum.',
                            slug: 'amet-libero-rerum',
                            image: { url: null, alt: 'Amet libero rerum.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/amet-libero-rerum',
                        },
                        categories: [
                            {
                                id: 6,
                                title: 'Amet libero rerum.',
                                slug: 'amet-libero-rerum',
                                image: { url: null, alt: 'Amet libero rerum.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/amet-libero-rerum',
                            },
                            {
                                id: 23,
                                title: 'Iure odio vel aperiam.',
                                slug: 'iure-odio-vel-aperiam',
                                image: { url: null, alt: 'Iure odio vel aperiam.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/iure-odio-vel-aperiam',
                            },
                        ],
                        image: { url: null, alt: 'Officiis.' },
                        url: 'http://localhost:8000/posts/amet-libero-rerum/officiis',
                    },
                    {
                        id: 77,
                        title: 'Quia id.',
                        slug: 'quia-id',
                        published_at: '2023-03-27',
                        description:
                            'Est odio fugiat cumque nesciunt hic. Doloremque dolor ratione omnis ut. Quidem fugiat sequi nulla repudiandae nobis iure blanditiis. Dolor ut dolorem maiores ut cupiditate consectetur modi.',
                        category: {
                            id: 5,
                            title: 'Dolores.',
                            slug: 'dolores',
                            image: { url: null, alt: 'Dolores.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/dolores',
                        },
                        categories: [
                            {
                                id: 5,
                                title: 'Dolores.',
                                slug: 'dolores',
                                image: { url: null, alt: 'Dolores.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/dolores',
                            },
                            {
                                id: 17,
                                title: 'Autem.',
                                slug: 'autem',
                                image: { url: null, alt: 'Autem.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/autem',
                            },
                        ],
                        image: { url: null, alt: 'Quia id.' },
                        url: 'http://localhost:8000/posts/dolores/quia-id',
                    },
                    {
                        id: 34,
                        title: 'Dolor.',
                        slug: 'dolor',
                        published_at: '2023-03-27',
                        description:
                            'Esse iure tempora ut sed at qui ipsum. Quo aliquid ab tenetur laboriosam voluptas itaque. Eum ut et rerum. Sit temporibus voluptatem eum eveniet.',
                        category: null,
                        categories: [],
                        image: { url: null, alt: 'Dolor.' },
                        url: null,
                    },
                    {
                        id: 85,
                        title: 'Ut nobis illo aut dicta.',
                        slug: 'ut-nobis-illo-aut-dicta',
                        published_at: '2023-03-27',
                        description:
                            'Illo facilis recusandae quibusdam optio non. Odit voluptas adipisci qui et dolores officia cum eaque. Vel quidem alias natus aperiam atque consequuntur.',
                        category: {
                            id: 6,
                            title: 'Amet libero rerum.',
                            slug: 'amet-libero-rerum',
                            image: { url: null, alt: 'Amet libero rerum.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/amet-libero-rerum',
                        },
                        categories: [
                            {
                                id: 6,
                                title: 'Amet libero rerum.',
                                slug: 'amet-libero-rerum',
                                image: { url: null, alt: 'Amet libero rerum.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/amet-libero-rerum',
                            },
                            {
                                id: 24,
                                title: 'Ipsam culpa.',
                                slug: 'ipsam-culpa',
                                image: { url: null, alt: 'Ipsam culpa.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/ipsam-culpa',
                            },
                        ],
                        image: { url: null, alt: 'Ut nobis illo aut dicta.' },
                        url: 'http://localhost:8000/posts/amet-libero-rerum/ut-nobis-illo-aut-dicta',
                    },
                    {
                        id: 20,
                        title: 'Dicta id.',
                        slug: 'dicta-id',
                        published_at: '2023-03-27',
                        description:
                            'Saepe occaecati aut totam ipsum rerum et. Laborum qui et quam. Sequi placeat omnis assumenda. Nostrum qui eveniet et nobis qui ut.',
                        category: {
                            id: 8,
                            title: 'Qui voluptate ut ipsum.',
                            slug: 'qui-voluptate-ut-ipsum',
                            image: { url: null, alt: 'Qui voluptate ut ipsum.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/qui-voluptate-ut-ipsum',
                        },
                        categories: [
                            {
                                id: 8,
                                title: 'Qui voluptate ut ipsum.',
                                slug: 'qui-voluptate-ut-ipsum',
                                image: { url: null, alt: 'Qui voluptate ut ipsum.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/qui-voluptate-ut-ipsum',
                            },
                            {
                                id: 15,
                                title: 'Praesentium qui.',
                                slug: 'praesentium-qui',
                                image: { url: null, alt: 'Praesentium qui.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/praesentium-qui',
                            },
                        ],
                        image: { url: null, alt: 'Dicta id.' },
                        url: 'http://localhost:8000/posts/qui-voluptate-ut-ipsum/dicta-id',
                    },
                    {
                        id: 25,
                        title: 'Enim nemo facilis eum est.',
                        slug: 'enim-nemo-facilis-eum-est',
                        published_at: '2023-03-27',
                        description:
                            'Nisi vero beatae est ullam. Minus ut quisquam in qui. Ratione et quos quidem quibusdam temporibus deserunt. Possimus non earum accusantium occaecati delectus.',
                        category: {
                            id: 25,
                            title: 'Non sint ut qui et.',
                            slug: 'non-sint-ut-qui-et',
                            image: { url: null, alt: 'Non sint ut qui et.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/non-sint-ut-qui-et',
                        },
                        categories: [
                            {
                                id: 25,
                                title: 'Non sint ut qui et.',
                                slug: 'non-sint-ut-qui-et',
                                image: { url: null, alt: 'Non sint ut qui et.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/non-sint-ut-qui-et',
                            },
                            {
                                id: 26,
                                title: 'Eos amet aut voluptatem.',
                                slug: 'eos-amet-aut-voluptatem',
                                image: { url: null, alt: 'Eos amet aut voluptatem.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/eos-amet-aut-voluptatem',
                            },
                        ],
                        image: { url: null, alt: 'Enim nemo facilis eum est.' },
                        url: 'http://localhost:8000/posts/non-sint-ut-qui-et/enim-nemo-facilis-eum-est',
                    },
                    {
                        id: 21,
                        title: 'Sint.',
                        slug: 'sint',
                        published_at: '2023-03-27',
                        description:
                            'Assumenda distinctio qui temporibus commodi beatae. Ullam iure qui accusamus quas maiores autem sapiente. Sed consequatur vitae cumque et consequatur at dolorem.',
                        category: null,
                        categories: [],
                        image: { url: null, alt: 'Sint.' },
                        url: null,
                    },
                    {
                        id: 61,
                        title: 'Nisi ut ut.',
                        slug: 'nisi-ut-ut',
                        published_at: '2023-03-27',
                        description:
                            'Iusto et sunt labore eius ut asperiores. Iusto ullam rerum autem reiciendis impedit possimus dolorem. Dicta aut provident adipisci in ut repellendus reprehenderit.',
                        category: {
                            id: 7,
                            title: 'Aut expedita.',
                            slug: 'aut-expedita',
                            image: { url: null, alt: 'Aut expedita.' },
                            icon: null,
                            url: 'http://localhost:8000/posts/aut-expedita',
                        },
                        categories: [
                            {
                                id: 7,
                                title: 'Aut expedita.',
                                slug: 'aut-expedita',
                                image: { url: null, alt: 'Aut expedita.' },
                                icon: null,
                                url: 'http://localhost:8000/posts/aut-expedita',
                            },
                        ],
                        image: { url: null, alt: 'Nisi ut ut.' },
                        url: 'http://localhost:8000/posts/aut-expedita/nisi-ut-ut',
                    },
                ],
                first_page_url: 'http://localhost:3000/blog?page=1',
                from: 1,
                last_page: 6,
                last_page_url: 'http://localhost:3000/blog?page=6',
                links: [
                    { url: null, label: '<', active: false },
                    { url: 'http://localhost:3000/blog?page=1', label: '1', active: true },
                    { url: 'http://localhost:3000/blog?page=2', label: '2', active: false },
                    { url: 'http://localhost:3000/blog?page=3', label: '3', active: false },
                    { url: 'http://localhost:3000/blog?page=4', label: '4', active: false },
                    { url: 'http://localhost:3000/blog?page=5', label: '5', active: false },
                    { url: 'http://localhost:3000/blog?page=6', label: '6', active: false },
                    { url: 'http://localhost:3000/blog?page=2', label: '>', active: false },
                ],
                next_page_url: 'http://localhost:3000/blog?page=2',
                path: 'http://localhost:3000/blog',
                per_page: 10,
                prev_page_url: null,
                to: 10,
                total: 58,
            },

            categories: [
                {
                    id: 20,
                    title: 'Qui nisi libero ut.',
                    slug: 'qui-nisi-libero-ut',
                    image: { url: null, alt: 'Qui nisi libero ut.' },
                    icon: null,
                    url: '/blog/qui-nisi-libero-ut',
                },
                {
                    id: 18,
                    title: 'Quis delectus natus.',
                    slug: 'quis-delectus-natus',
                    image: { url: null, alt: 'Quis delectus natus.' },
                    icon: null,
                    url: '/blog/quis-delectus-natus',
                },
                {
                    id: 14,
                    title: 'Enim.',
                    slug: 'enim',
                    image: { url: null, alt: 'Enim.' },
                    icon: null,
                    url: '/blog/enim',
                },
                {
                    id: 12,
                    title: 'Itaque modi quia qui.',
                    slug: 'itaque-modi-quia-qui',
                    image: { url: null, alt: 'Itaque modi quia qui.' },
                    icon: null,
                    url: '/blog/itaque-modi-quia-qui',
                },
                {
                    id: 11,
                    title: 'Exercitationem enim.',
                    slug: 'exercitationem-enim',
                    image: { url: null, alt: 'Exercitationem enim.' },
                    icon: null,
                    url: '/blog/exercitationem-enim',
                },
                {
                    id: 10,
                    title: 'Qui quia officiis odio.',
                    slug: 'qui-quia-officiis-odio',
                    image: { url: null, alt: 'Qui quia officiis odio.' },
                    icon: null,
                    url: '/blog/qui-quia-officiis-odio',
                },
                {
                    id: 9,
                    title: 'Omnis ad rerum.',
                    slug: 'omnis-ad-rerum',
                    image: { url: null, alt: 'Omnis ad rerum.' },
                    icon: null,
                    url: '/blog/omnis-ad-rerum',
                },
                {
                    id: 7,
                    title: 'Et atque.',
                    slug: 'et-atque',
                    image: { url: null, alt: 'Et atque.' },
                    icon: null,
                    url: '/blog/et-atque',
                },
                {
                    id: 4,
                    title: 'Nihil debitis officia quam.',
                    slug: 'nihil-debitis-officia-quam',
                    image: { url: null, alt: 'Nihil debitis officia quam.' },
                    icon: null,
                    url: '/blog/nihil-debitis-officia-quam',
                },
            ],
        }
    },

    created() {
        this.categories.unshift({ title: 'Tất cả', url: this.$router.resolve({ name: 'blog' }).fullPath })
    },
}
</script>
