<template>
    <JPageJobs :jobs="jobs" />
</template>
<script>
export default {
    data() {
        return {
            jobs: [
                {
                    id: 18,
                    title: 'Principal Python Engineer',
                    slug: 'principal-python-engineer',
                    is_urgent: 1,
                    is_bonus: 1,
                    is_available: 1,
                    category: 'Tech/Engineer',
                    location: 'Ho Chi Minh',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 20,
                    title: 'Principal Ruby on Rails Engineer',
                    slug: 'principal-ruby-on-rails-engineer',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Ho Chi Minh',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 26,
                    title: 'Middle/Senior Ruby on Rails Engineer',
                    slug: 'middlesenior-ruby-on-rails-engineer',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Ho Chi Minh',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 28,
                    title: 'Principal Ruby on Rails Engineer',
                    slug: 'principal-ruby-on-rails-engineer1',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Hanoi',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 27,
                    title: 'Senior Java Engineer',
                    slug: 'senior-java-engineer',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Hanoi',
                    quantity: 3,
                    url: '/jobs/job-detail',
                },
                {
                    id: 21,
                    title: 'Golang Technical Leader',
                    slug: 'golang-technical-leader',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Hanoi',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 17,
                    title: 'Senior QA/QC Engineer (Manual Tester)',
                    slug: 'senior-qaqc-engineer-manual-tester',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Ho Chi Minh',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 16,
                    title: 'Middle/Senior Golang Engineer',
                    slug: 'middlesenior-golang-engineer',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Ho Chi Minh',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 15,
                    title: 'Product Management Department Manager',
                    slug: 'product-management-department-manager',
                    is_urgent: 1,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Ho Chi Minh',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 23,
                    title: 'Senior Front-end Engineer (ReactJS)',
                    slug: 'senior-front-end-engineer-reactjs',
                    is_urgent: 0,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Hanoi',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
                {
                    id: 22,
                    title: 'Senior/Principal QA/QC',
                    slug: 'seniorprincipal-qaqc',
                    is_urgent: 0,
                    is_bonus: 0,
                    category: 'Tech/Engineer',
                    location: 'Hanoi',
                    quantity: 1,
                    url: '/jobs/job-detail',
                },
            ],
        }
    },
}
</script>
